baseURL = 'http://192.168.1.170/'
locale = 'eng'
title = 'Ultimate Gates of Hell'
theme = 'PaperMod'

[params]
env = 'production'
title = 'Ultimate Gates of Hell'
description = ''
defaultTheme = 'dark'
showToc = false
favicon = "/favicon.ico"
appleTouchIcon = "/apple-touch-icon.png"

[[menu.main]]
name = "Framedata"
pageRef = "/framedata"
weight = 1

[[menu.main]]
name = "Combos"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Matchups"
pageRef = "/matchups"
weight = 3

[[menu.main]]
name = "Stages"
url = "/stages/"
weight = 4

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true