baseURL = 'https://Aoex2612.github.io/Ultimate-Gates-of-Hell/'
relativeURLs = false
canonifyURLs = false
locale = 'eng'
title = 'Ultimate Gates of Hell'
theme = 'PaperMod'

[params]
env = 'production'
title = 'Ultimate Gates of Hell'
description = ''
defaultTheme = 'dark'
showToc = false

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon-96x96.png"
favicon32x32 = "favicon-96x96.png"
apple_touch_icon = "apple-touch-icon.png"

[[menu.main]]
name = "Framedata"
url = "framedata"
weight = 1

[[menu.main]]
name = "Combos"
url = "combos"
weight = 2

[[menu.main]]
name = "Matchups"
url = "matchups"
weight = 3

[[menu.main]]
name = "Stages"
url = "stages"
weight = 4

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
